"""Add index to concepts labels

Revision ID: 25fbb72964b9
Revises: 2d17a9a6e59f
Create Date: 2024-10-27 10:27:54.244677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25fbb72964b9'
down_revision: Union[str, None] = '2d17a9a6e59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_labels_concept_id'), 'labels', ['concept_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labels_concept_id'), table_name='labels')
    # ### end Alembic commands ###
