"""Add index to concepts join table

Revision ID: 2d17a9a6e59f
Revises: 9027268e7348
Create Date: 2024-10-27 10:26:21.828573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d17a9a6e59f'
down_revision: Union[str, None] = '9027268e7348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_references_subjects_table_concept_id'), 'references_subjects_table', ['concept_id'], unique=False)
    op.create_index(op.f('ix_references_subjects_table_reference_id'), 'references_subjects_table', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_subjects_table_reference_id'), table_name='references_subjects_table')
    op.drop_index(op.f('ix_references_subjects_table_concept_id'), table_name='references_subjects_table')
    # ### end Alembic commands ###
