"""Add index to reference manifestations

Revision ID: 3338d07cab29
Revises: 3d1eecb146bb
Create Date: 2024-10-27 10:21:43.958920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3338d07cab29'
down_revision: Union[str, None] = '3d1eecb146bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reference_manifestations_reference_id'), 'reference_manifestations', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_manifestations_reference_id'), table_name='reference_manifestations')
    # ### end Alembic commands ###
