"""Add indexes to reference_event

Revision ID: 3aa20880ce26
Revises: 125e4e37aaed
Create Date: 2024-10-27 14:03:18.629780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aa20880ce26'
down_revision: Union[str, None] = '125e4e37aaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reference_events_harvesting_id'), 'reference_events', ['harvesting_id'], unique=False)
    op.create_index(op.f('ix_reference_events_reference_id'), 'reference_events', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_events_reference_id'), table_name='reference_events')
    op.drop_index(op.f('ix_reference_events_harvesting_id'), table_name='reference_events')
    # ### end Alembic commands ###
