"""Add index to abstracts foreign key to reference

Revision ID: 3c097a1d478b
Revises: 808af9258e7f
Create Date: 2024-10-27 10:01:59.870936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c097a1d478b'
down_revision: Union[str, None] = '808af9258e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_abstracts_reference_id'), 'abstracts', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abstracts_reference_id'), table_name='abstracts')
    # ### end Alembic commands ###
