"""Add index to affiliations

Revision ID: 5dbadbba8362
Revises: ce8760a184c1
Create Date: 2024-10-27 10:12:38.887627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbadbba8362'
down_revision: Union[str, None] = 'ce8760a184c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_affiliations_table_contribution_id'), 'affiliations_table', ['contribution_id'], unique=False)
    op.create_index(op.f('ix_affiliations_table_organization_id'), 'affiliations_table', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliations_table_organization_id'), table_name='affiliations_table')
    op.drop_index(op.f('ix_affiliations_table_contribution_id'), table_name='affiliations_table')
    # ### end Alembic commands ###
