"""Add index to reference identifiers

Revision ID: 6f89220087a9
Revises: 5dbadbba8362
Create Date: 2024-10-27 10:17:28.544620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f89220087a9'
down_revision: Union[str, None] = '5dbadbba8362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reference_identifiers_reference_id'), 'reference_identifiers', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_identifiers_reference_id'), table_name='reference_identifiers')
    # ### end Alembic commands ###
