"""Add index to harvesting

Revision ID: 7a38338c5984
Revises: 9a14bd341cf1
Create Date: 2024-10-27 13:55:41.824916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a38338c5984'
down_revision: Union[str, None] = '9a14bd341cf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_harvestings_retrieval_id'), 'harvestings', ['retrieval_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_harvestings_retrieval_id'), table_name='harvestings')
    # ### end Alembic commands ###
