"""Add structured names to contributors

Revision ID: 7ffdecaed84f
Revises: 9ac659c0ab9f
Create Date: 2025-01-29 10:31:44.025960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ffdecaed84f'
down_revision: Union[str, None] = '9ac659c0ab9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('contributors', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('contributors', sa.Column('structured_name_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributors', 'structured_name_variants')
    op.drop_column('contributors', 'last_name')
    op.drop_column('contributors', 'first_name')
    # ### end Alembic commands ###
