"""Add index to subtitles

Revision ID: 9027268e7348
Revises: 3338d07cab29
Create Date: 2024-10-27 10:23:10.701049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9027268e7348'
down_revision: Union[str, None] = '3338d07cab29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subtitles_reference_id'), 'subtitles', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subtitles_reference_id'), table_name='subtitles')
    # ### end Alembic commands ###
