"""Add external person identifiers to contributors

Revision ID: 92e657c18598
Revises: 3aa20880ce26
Create Date: 2024-12-21 09:50:48.890591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e657c18598'
down_revision: Union[str, None] = '3aa20880ce26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_person_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_person_identifiers_contributor_id'), 'external_person_identifiers', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_external_person_identifiers_source'), 'external_person_identifiers', ['source'], unique=False)
    op.create_index(op.f('ix_external_person_identifiers_type'), 'external_person_identifiers', ['type'], unique=False)
    op.create_index(op.f('ix_external_person_identifiers_value'), 'external_person_identifiers', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_person_identifiers_value'), table_name='external_person_identifiers')
    op.drop_index(op.f('ix_external_person_identifiers_type'), table_name='external_person_identifiers')
    op.drop_index(op.f('ix_external_person_identifiers_source'), table_name='external_person_identifiers')
    op.drop_index(op.f('ix_external_person_identifiers_contributor_id'), table_name='external_person_identifiers')
    op.drop_table('external_person_identifiers')
    # ### end Alembic commands ###
