"""Add contributor identifiers to contributors

Revision ID: 9ac659c0ab9f
Revises: 3aa20880ce26
Create Date: 2024-12-22 16:36:25.339255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ac659c0ab9f'
down_revision: Union[str, None] = '3aa20880ce26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributor_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('contributor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contributor_identifier_contributor_id'), 'contributor_identifier', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_contributor_identifier_source'), 'contributor_identifier', ['source'], unique=False)
    op.create_index(op.f('ix_contributor_identifier_type'), 'contributor_identifier', ['type'], unique=False)
    op.create_index(op.f('ix_contributor_identifier_value'), 'contributor_identifier', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributor_identifier_value'), table_name='contributor_identifier')
    op.drop_index(op.f('ix_contributor_identifier_type'), table_name='contributor_identifier')
    op.drop_index(op.f('ix_contributor_identifier_source'), table_name='contributor_identifier')
    op.drop_index(op.f('ix_contributor_identifier_contributor_id'), table_name='contributor_identifier')
    op.drop_table('contributor_identifier')
    # ### end Alembic commands ###
