"""Create external person identifiers

Revision ID: a33110d9d5d9
Revises: 3aa20880ce26
Create Date: 2024-12-20 05:15:18.025654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33110d9d5d9'
down_revision: Union[str, None] = '3aa20880ce26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_person_identifiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'type', 'value')
    )
    op.create_index(op.f('ix_external_person_identifiers_source'), 'external_person_identifiers', ['source'], unique=False)
    op.create_index(op.f('ix_external_person_identifiers_type'), 'external_person_identifiers', ['type'], unique=False)
    op.create_index(op.f('ix_external_person_identifiers_value'), 'external_person_identifiers', ['value'], unique=False)
    op.create_table('contributor_identifiers_table',
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.Column('external_person_identifier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['external_person_identifier_id'], ['external_person_identifiers.id'], )
    )
    op.create_index(op.f('ix_contributor_identifiers_table_contributor_id'), 'contributor_identifiers_table', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_contributor_identifiers_table_external_person_identifier_id'), 'contributor_identifiers_table', ['external_person_identifier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributor_identifiers_table_external_person_identifier_id'), table_name='contributor_identifiers_table')
    op.drop_index(op.f('ix_contributor_identifiers_table_contributor_id'), table_name='contributor_identifiers_table')
    op.drop_table('contributor_identifiers_table')
    op.drop_index(op.f('ix_external_person_identifiers_value'), table_name='external_person_identifiers')
    op.drop_index(op.f('ix_external_person_identifiers_type'), table_name='external_person_identifiers')
    op.drop_index(op.f('ix_external_person_identifiers_source'), table_name='external_person_identifiers')
    op.drop_table('external_person_identifiers')
    # ### end Alembic commands ###
