"""Register issued dates as strings

Revision ID: b4ce17110a72
Revises: 7ffdecaed84f
Create Date: 2025-02-06 07:47:44.867734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ce17110a72'
down_revision: Union[str, None] = '7ffdecaed84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('references', sa.Column('raw_issued', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('references', 'raw_issued')
    # ### end Alembic commands ###
