"""Add index to organisation_identifiers reference to organisation

Revision ID: ce8760a184c1
Revises: e77d3d377958
Create Date: 2024-10-27 10:11:02.536686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce8760a184c1'
down_revision: Union[str, None] = 'e77d3d377958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_organization_identifiers_organization_id'), 'organization_identifiers', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_identifiers_organization_id'), table_name='organization_identifiers')
    # ### end Alembic commands ###
