"""Add index to document types

Revision ID: e66091f3c19c
Revises: 25fbb72964b9
Create Date: 2024-10-27 10:29:11.990747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66091f3c19c'
down_revision: Union[str, None] = '25fbb72964b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_references_document_types_table_document_type_id'), 'references_document_types_table', ['document_type_id'], unique=False)
    op.create_index(op.f('ix_references_document_types_table_reference_id'), 'references_document_types_table', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_document_types_table_reference_id'), table_name='references_document_types_table')
    op.drop_index(op.f('ix_references_document_types_table_document_type_id'), table_name='references_document_types_table')
    # ### end Alembic commands ###
