"""Add index to references

Revision ID: e6c4f376a58e
Revises: 7a38338c5984
Create Date: 2024-10-27 13:57:19.484890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c4f376a58e'
down_revision: Union[str, None] = '7a38338c5984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_references_book_id'), 'references', ['book_id'], unique=False)
    op.create_index(op.f('ix_references_issue_id'), 'references', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_references_issue_id'), table_name='references')
    op.drop_index(op.f('ix_references_book_id'), table_name='references')
    # ### end Alembic commands ###
